<div class="row justify-content-center">
	<div class="col-sm-10 col-md-10 col-lg-6 col-xl-6">
		<div class="card shadow mb-4">
			<div class="card-header py-3">
				<h6 class="m-0 font-weight-bold text-primary">ATUALIZAR DADOS USUÁRIO</h6>
			</div>
			<div class="card-body">
				<form id="formUserEdit" name="formUserEdit" method="POST" action="/user/update">
					<input type="hidden" class="form-control" id="id" name="id" value="<?= $this->user->id;?>">
					<div class="form-group">
						<label for="access_level">Nível de Acesso</label>
						<select class="form-control" name="access_level">
							<option value="">Selecione...</option>
							<?php if (is_array($this->accessLevels) && !empty($this->accessLevels)) : ?>
								<?php foreach ($this->accessLevels as $access) : ?>
									<option value="<?= $access->id;?>" <?= $access->id === $this->user->access_level_id ? 'selected' : '';?>><?= $access->description;?></option>
								<?php endforeach; ?>
							<?php endif; ?>
						</select>
					</div>
					<div class="form-group">
						<label for="email">E-mail</label>
						<input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="email@exemplo.com.br" required value="<?= $this->user->email;?>">
						<small id="emailHelp" class="form-text text-info">Nunca iremos compartilhar seu e-mail com ninguém.</small>
					</div>
					<div class="form-group">
						<label for="password">Senha</label>
						<input type="password" class="form-control" id="password" name="password" placeholder="**********" required>
					</div>
					<button id="btnFormUserEdit" type="button" class="btn btn-primary">Salvar</button>
				</form>
			</div>
		</div>
	</div>
</div>
