<h2>Cadastrar Usuário</h2>
<form id="formUserAccess" name="formUserAccess" method="POST" action="">
	<div class="form-group">
		<label for="email">E-mail</label>
		<input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="email@exemplo.com.br" required>
		<small id="emailHelp" class="form-text text-info">Nunca iremos compartilhar seu e-mail com ninguém.</small>
	</div>
	<div class="form-group">
		<label for="password">Senha</label>
		<input type="password" class="form-control" id="password" name="password" placeholder="**********">
	</div>
	<button id="btnFormUserAccess" type="button" class="btn btn-primary">Salvar</button>
</form>

