				</div> <!-- div container -->
			</div> <!-- div row -->
		</div> <!-- div container-fluid -->
	<script src="<?= JS_PATH;?>/jquery-3.3.1.min.js" type="text/javascript"></script>
	<script src="<?= JS_PATH;?>/bootstrap.min.js" type="text/javascript"></script>
	<script src="<?= JS_PATH;?>/functions.js" type="text/javascript"></script>
	<?php if (isset($this->data['controller']) && isset($this->data['viewName'])) : ?>

		<script src="<?= JS_PATH;?>/<?= $this->controller;?>/<?= $this->viewName;?>.js" type="text/javascript"></script>

	<?php else: ?>

		<script src="<?= JS_PATH;?>/<?= $this->controller;?>/<?= $this->controller;?>.js" type="text/javascript"></script>

	<?php endif; ?>
	<?php require VIEWS_INCLUDES_PATH . DIRECTORY_SEPARATOR . 'modal-alert.phtml'; ?>
	</body>
</html>