				</div> <!-- div container -->
			</div> <!-- div row -->
		</div> <!-- div container-fluid -->
	<script src="<?= JS_PATH;?>/jquery-3.3.1.min.js" type="text/javascript"></script>
	<script src="<?= JS_PATH;?>/bootstrap.min.js" type="text/javascript"></script>

	<?php if (isset($this->data['controller'])) : ?>

	<script src="<?= JS_PATH;?>/<?= $this->controller;?>/<?= $this->viewName;?>.js" type="text/javascript"></script>

	<?php endif; ?>

	</body>
</html>