			</div>
			<!-- /.container-fluid -->

		</div>
		<!-- End of Main Content -->

		<!-- Footer -->
		<footer class="sticky-footer bg-white">
			<div class="container my-auto">
				<div class="copyright text-center my-auto">
					<span>Copyright &copy; <span class="badge badge-primary">Gomes</span> 2019</span>
				</div>
			</div>
		</footer>
		<!-- End of Footer -->

	    </div>
	    <!-- End of Content Wrapper -->

	</div>
	<!-- End of Page Wrapper -->

	<!-- Scroll to Top Button-->
	<a class="scroll-to-top rounded" href="#page-top">
		<i class="fas fa-angle-up"></i>
	</a>
	<script src="<?= JS_PATH;?>/jquery/jquery-3.3.1.min.js" type="text/javascript"></script>
	<script src="<?= JS_PATH;?>/bootstrap/bootstrap.min.js" type="text/javascript"></script>
	<script src="<?= JS_PATH;?>/bootstrap/bootstrap.bundle.min.js" type="text/javascript"></script>
	<script src="<?= JS_PATH;?>/jquery/jquery.validate.min.js" type="text/javascript"></script>
	<script src="<?= JS_PATH;?>/jquery/additional-methods.js" type="text/javascript"></script>
	<script src="<?= JS_PATH;?>/jquery/jquery.mask.min.js" type="text/javascript"></script>
	<script src="<?= JS_PATH;?>/jquery/jquery.easing.min.js" type="text/javascript"></script>
	<script src="<?= JS_PATH;?>/global/functions.js" type="text/javascript"></script>
	<script src="<?= JS_PATH;?>/global/sb-admin-2.min.js" type="text/javascript"></script>

	<?php if (isset($this->controller) && isset($this->viewName)) : ?>

		<script src="<?= JS_PATH;?>/<?= $this->controller;?>/<?= $this->viewName;?>.js" type="text/javascript"></script>
		<script src="<?= JS_PATH;?>/<?= $this->controller;?>/<?= $this->controller;?>.js" type="text/javascript"></script>

	<?php elseif (isset($this->controller)) : ?>

		<script src="<?= JS_PATH;?>/<?= $this->controller;?>/<?= $this->controller;?>.js" type="text/javascript"></script>

	<?php endif; ?>
	<?php require VIEWS_INCLUDES_PATH . DIRECTORY_SEPARATOR . 'modal-alert.phtml'; ?>
	</body>
</html>