<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>CRUD POWER</title>
		<link rel="stylesheet" type="text/css" href="<?= ASSETS_PATH;?>/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="<?= ASSETS_PATH;?>/css/style.css">
		<link rel="icon" href="<?= ASSETS_PATH;?>/img/favicon.png">
		<link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	</head>
	<body>
		<div class="container-fluid">
		<?php
		if($this->menu) {
			require VIEWS_INCLUDES_PATH . '/menu.phtml';
		}
		?>
			<div class="row">
				<div class="container">
