<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="navbar-brand text-center" href="/">
        <img src="<?= ASSETS_PATH;?>/img/logo.png" class="img-fluid">
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link py-1" href="/">
            <span>Home</span>
        </a>
    </li>

    <hr class="sidebar-divider my-0">

    <li class="nav-item">
        <a class="nav-link py-1" href="/about">
            <span>Sobre</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <?php if (\System\Session\Session::has('USER')) : ?>
        <!-- Heading -->
        <div class="sidebar-heading">
            Usuário
        </div>

         <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#menuItemsExpense" aria-expanded="true" aria-controls="menuItemsExpense">
                <i class="fas fa-file-invoice-dollar"></i>
                <span>Despesas</span>
            </a>
            <div id="menuItemsExpense" class="collapse" aria-labelledby="headingThree" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Ações:</h6>
                    <a class="collapse-item" href="/expense/list">Listar</a>
                    <a class="collapse-item" href="/expense/register">Cadastrar</a>
                </div>
            </div>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <?php if (\System\Session\Session::get('ACCESS_LEVEL') === \System\Constants::ACCESS_LEVEL[1]) : ?>
            <div class="sidebar-heading">
                Administrativo
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#menuItemsUser" aria-expanded="true" aria-controls="menuItemsUser">
                    <i class="fas fa-users"></i>
                    <span>Usuários</span>
                </a>
                <div id="menuItemsUser" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Ações:</h6>
                        <a class="collapse-item" href="/user/list">Listar</a>
                        <a class="collapse-item" href="/user/register">Cadastrar</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#menuItemsCategory" aria-expanded="true" aria-controls="menuItemsCategory">
                    <i class="fas fa-layer-group"></i>
                    <span>Categorias</span>
                </a>
                <div id="menuItemsCategory" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Ações:</h6>
                        <a class="collapse-item" href="/category/list">Listar</a>
                        <a class="collapse-item" href="/category/register">Cadastrar</a>
                    </div>
                </div>
            </li>
        <?php endif; ?>
    <?php endif; ?>

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>