<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <a class="navbar-brand" href="/home">
        <img src="<?= IMG_PATH;?>/logo-bar-do-gomes.png" width="100" alt="Logomarca Gomes">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Usuário
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/user/list">Listar</a>
                  <a class="dropdown-item" href="/user/register">Cadastrar</a>
              </div>
          </li>
        </ul>
        <div class="dropdown">
            <a class="btn bg-transparent" type="button" id="dropdownMenuButton" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
                <i class="far fa-user-circle"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg-right bg-dark" aria-labelledby="dropdownMenuButton">
                <form class="dropdown-item bg-dark">
                    <div class="card" style="width: 18rem;">
                        <img src="<?=IMG_PATH;?>/thumbnail.png" class="card-img-top img-thumbnail" alt="Logo Gomes">
                        <div class="card-body">
                            <div class="form-group">
                                <label class="card-subtitle mb-2 text-secondary" for="email">Email</label>
                                <input type="email" class="form-control form-control-sm" id="email" aria-describedby="emailHelp" placeholder="E-mail">
                            </div>
                            <div class="form-group">
                                <label class="card-subtitle mb-2 text-secondary" for="password">Senha</label>
                                <input type="password" class="form-control form-control-sm" id="password" placeholder="Senha">
                            </div>
                            <div class="form-group row justify-content-center py-1 my-2">
                                <button type="submit" class="btn btn-primary btn-sm text-center">Entrar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</nav>