<div id="modal-alert" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content modal-border">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="redirect" name="redirect">
                <div class="row">
                    <div class="col content text-center text-muted font-weight-light">
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col text-center">
                        <button id="btnModalAlert" type="button" class="btn btn-sm btn-block" data-dismiss="modal">OK</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>