CREATE DATABASE IF NOT EXISTS omni;
USE omni;

DROP TABLE IF EXISTS ACCESS_LEVEL;
CREATE TABLE IF NOT EXISTS ACCESS_LEVEL
(
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	description VARCHAR(255) UNIQUE NOT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = Latin1;

INSERT INTO ACCESS_LEVEL (description) VALUES('ADMIN');
INSERT INTO ACCESS_LEVEL (description) VALUES('USER');

DROP TABLE IF EXISTS USER_ACCESS;
CREATE TABLE IF NOT EXISTS USER_ACCESS
(
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	email VARCHAR(80) UNIQUE NOT NULL,
	password VARCHAR(72) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at DATETIME,
	access_level_id INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT user_access_level_id
	FOREIGN KEY fk_user_acess_level_id(access_level_id)
	REFERENCES ACCESS_LEVEL(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET = Latin1;

DROP TABLE IF EXISTS USER;
CREATE TABLE IF NOT EXISTS USER
(
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	cpf VARCHAR(15) NOT NULL,
	gender CHAR(1) NOT NULL,
	birthdate DATETIME NOT NULL,
	cellphone VARCHAR(18) NOT NULL,
	address VARCHAR(255) NOT NULL,
    address_num VARCHAR(5) NOT NULL,
    address_compl VARCHAR(80),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at DATETIME,
	user_acess_id INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT user_access_id
	FOREIGN KEY fk_user_acess_id(user_acess_id)
	REFERENCES USER_ACCESS(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET = Latin1;

