<div class="row justify-content-center">
    <div class="col-sm-10 col-md-10 col-lg-6 col-xl-6">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h5 class="m-0 font-weight-bold text-primary">LOGIN</h5>
            </div>
            <div class="card-body">
               <form id="formAuthLogin" name="formAuthLogin" action="/auth/validateLogin" method="POST">
                   <div class="form-row">
                       <div class="form-group col">
                           <label for="inputEmail4">Email</label>
                           <input name="email" type="email" class="form-control" id="inputEmail4" placeholder="Email" required data-validation="required">
                       </div>
                   </div>
                   <div class="form-row">
                       <div class="form-group col">
                           <label for="inputPassword4">Password</label>
                           <input name="password" type="password" class="form-control" id="inputPassword4" placeholder="Password" required data-validation="required" maxlength="8">
                       </div>
                   </div>
                   <a href="/auth/createAccount" title="">Cadastre-se</a>
                   <button id="btnFormAuthLogin" type="button" class="btn btn-primary float-right">Login</button>
               </form>
            </div>
        </div>
    </div>
</div>
