<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Login</h5>
            </div>
            <div class="card-body">
                <form id="formAuthLogin" name="formAuthLogin" action="/auth/validateLogin" method="POST">
                    <div class="form-row">
                        <div class="form-group col">
                            <label for="inputEmail4">Email</label>
                            <input name="email" type="email" class="form-control" id="inputEmail4" placeholder="Email" data-validation="required">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col">
                            <label for="inputPassword4">Password</label>
                            <input name="password" type="password" class="form-control" id="inputPassword4" placeholder="Password" data-validation="required" maxlength="8">
                        </div>
                    </div>
                    <a href="/auth/createAccount" title="">Cadastre-se</a>
                    <button id="btnFormAuthLogin" type="button" class="btn btn-primary float-right">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>
