<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Cadastro</h5>
            </div>
            <div class="card-body">
                <form id="formAuthRegister" name="formAuthRegister" action="/auth/register" method="POST">
                    <div class="form-group">
                        <label for="inputEmail4">E-mail</label>
                        <input name="email" type="email" class="form-control" id="inputEmail4" placeholder="exemplo@email.com">
                    </div>
                    <div class="form-group">
                        <label for="inputPassword4">Senha</label>
                        <input id="password" name="password" type="password" class="form-control" placeholder="********">
                    </div>
                    <div class="form-group">
                        <label for="inputPassword4">Confirme a senha</label>
                        <input id="confirPassword" name="confirPassword" type="password" class="form-control" placeholder="********">
                    </div>
                    <button id="btnFormAuthRegister" type="button" class="btn btn-success float-right">Cadastrar</button>
                </form>
            </div>
        </div>
    </div>
</div>
