<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Cadastro</h5>
            </div>
            <div class="card-body">
                <form id="formAuthRegister" name="formAuthRegister" action="/auth/register" method="POST">
                    <h5>DADOS PESSOAIS</h5>
                    <div class="form-group">
                        <label for="name">Nome Completo</label>
                        <input id="name" name="name" type="text" class="form-control" placeholder="Ex. João da Silva" data-validation="required">
                    </div>
                    <div class="form-group">
                        <label for="cpf">CPF</label>
                        <input id="cpf" name="cpf" type="text" class="form-control" placeholder="Ex. xxx.xxx.xxx-xx">
                    </div>
                    <fieldset class="form-group">
                        <div class="row">
                            <legend class="col-form-label col-sm-2 pt-0">Gênero</legend>
                            <div class="col-sm-10">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="genero" id="generoM" value="M" checked>
                                    <label class="form-check-label" for="generoM">Masculino</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="genero" id="generoF" value="F">
                                    <label class="form-check-label" for="generoF">Feminino</label>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <div class="form-group">
                        <label for="birthdate">Data de Nascimento</label>
                        <input id="birthdate" name="birthdate" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="cellphone">Celular</label>
                        <input id="cellphone" name="cellphone" type="text" class="form-control" placeholder="(xx) xxxx-xxxx">
                    </div>
                    <div class="form-group">
                        <label for="address">Endereço</label>
                        <input id="address" name="address" type="text" class="form-control" placeholder="Ex. Rua, Travessa, Avenida ...">
                    </div>
                    <div class="form-group">
                        <label for="address_num">N.º</label>
                        <input id="address_num" name="address_num" type="text" class="form-control" placeholder="Ex. 9999" maxlength="4">
                    </div>
                    <div class="form-group">
                        <label for="address_compl">Complemento</label>
                        <input id="address_compl" name="address_compl" type="text" class="form-control" placeholder="Ex. Bloco B">
                    </div>
                    <h5>DADOS DE ACESSO</h5>
                    <div class="form-group">
                        <label for="inputEmail4">E-mail</label>
                        <input name="email" type="email" class="form-control" id="inputEmail4" placeholder="exemplo@email.com">
                    </div>
                    <div class="form-group">
                        <label for="inputPassword4">Senha</label>
                        <input id="password" name="password" type="password" class="form-control" placeholder="********" maxlength="8">
                    </div>
                    <div class="form-group">
                        <label for="inputPassword4">Confirme a senha</label>
                        <input id="confirmPassword" name="confirmPassword" type="password" class="form-control" placeholder="********" maxlength="8">
                    </div>
                    <button id="btnFormAuthRegister" type="button" class="btn btn-success float-right">Cadastrar</button>
                </form>
            </div>
        </div>
    </div>
</div>
