<div class="row justify-content-center">
    <div class="col-sm-10 col-md-10 col-lg-6 col-xl-6">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">CADASTRAR DESPESA</h6>
            </div>
            <div class="card-body">
                <form id="formRegisterExpense" name="formRegisterExpense" method="POST" action="">
                    <input type="hidden" name="user_access_id" value="<?= \System\Session\Session::get('USER_ID');?>">
                    <div class="form-group">
                        <label for="category_id">Categoria</label>
                        <select class="form-control" name="category_id">
                            <option value="">Selecione...</option>
                            <?php if (is_array($this->categories) && !empty($this->categories)) : ?>
                                <?php foreach ($this->categories as $category) : ?>
                                    <option value="<?= $category->id;?>"><?= $category->description;?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="description">Descrição</label>
                        <input type="description" class="form-control" id="description" name="description" required data-validation="required">
                    </div>
                    <div class="form-group">
                        <label for="value">Valor</label>
                        <input type="value" class="form-control" id="value" name="value" required data-validation="required">
                    </div>
                    <button id="btnFormRegisterExpense" type="button" class="btn btn-primary float-right">Salvar</button>
                </form>
            </div>
        </div>
    </div>
</div>