<div class="row align-items-center">
    <div class="col text-center">
        <div class="error mx-auto text-<?= $this->class;?>" data-text="<?= $this->title;?>"><?= $this->title;?></div>
        <p class="lead text-gray-800 mb-3 font-weight-bold"><?= $this->code . ' : ' . $this->message;?></p>
        <p class="text-gray-500 mb-1">Parece que há uma falha na matrix...</p>
        <a href="<?= $_SERVER['HTTP_REFERER'] ?? '/';?>" class="btn btn-primary btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-arrow-left"></i>
            </span>
            <span class="text"><strong><span class="text-info">VOLTAR</span></strong></span>
        </a>
    </div>
</div>