<div class="row align-items-center justify-content-center">
    <div class="col-sm-6 text-center mt-5">
        <div class="card rounded">
            <h2 class="font-weight-bold card-header text-<?= $this->class;?>">
                <?= $this->title;?>
            </h2>
            <div class="card-body">
                <h5 class="card-title font-weight-bold text-danger"><?= $this->code . ' : ' . $this->message;?></h5>
                <p class="card-text small" style="font-family: Titillium Web;"><em>Parece que há uma falha na matrix...</em></p>
                <a href="<?= $_SERVER['HTTP_REFERER'] ?? '/';?>" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                    <span class="text"><strong><span class="text-info">VOLTAR</span></strong></span>
                </a>
            </div>
        </div>
    </div>
</div>