<div class="row justify-content-center mb-2">
    <div class="col-6 col-sm-3 col-md-8 col-lg-10">
        <h5 class="font-weight-bold text-primary">CONTATO</h5>
    </div>
</div>
<div class="row justify-content-center mb-3">
    <div class="col-8 col-sm-8 col-md-10 col-lg-10">
        <form id="formContact" name="formContact" action="/contact/sendEmailContact" method="POST">
            <div class="form-group">
                <label for="nome">Nome:</label>
                <input id="nome" name="nome" type="text" class="form-control" placeholder="Digite o nome completo">
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="email">E-mail</label>
                    <input id="email" name="email" type="email" class="form-control" placeholder="exemplo@email.com.br">
                </div>
                <div class="form-group col-md-6">
                    <label for="telefone">Contato</label>
                    <input id="telefone" name="telefone" type="tel" class="form-control" placeholder="(00) 0 0000-0000">
                </div>
            </div>
            <div class="form-group">
                <label for="mensagem">Mensagem</label>
                <textarea id="mensagem" name="mensagem" class="form-control" rows="4" maxlength="255"></textarea>
                <small id="mensagem_help" name="mensagem_help" class="form-text text-primary"></small>
            </div>
            <a class="btn btn-sm btn-primary" href="/contact/table" title=""><i class="far fa-envelope"></i> Tabela</a>
            <!-- <button id="btnSubmitFormContact" name="btnSubmitFormContact" type="button" class="btn btn-primary btn-sm float-right"><i class="far fa-envelope"></i> Enviar</button> -->
        </form>
    </div>
</div>