<?php require VIEWS_INCLUDES_PATH . DIRECTORY_SEPARATOR . 'message.phtml'; ?>
<div class="jumbotron">
	<h1 class="display-4 font-weight-bold text-primary">BEM-VINDO AO CRUDD! <i class="far fa-smile-wink"></i></h1>
	<h3 class="text-info font-weight-bold">Projeto Bem Simples</h3>
	<hr class="my-4">
	<p class="small text-muted">
		Projeto construído para aplicação de novos conhecimentos.
		Conceitos aplicados:
	</p>
	<ul>
		<li>
			PHP:
			<ul>
				<li>Versão: <span class="span-information">7.3</span></li>
				<li>Conexão e Interação com Banco de Dados: <span class="span-information">PDO - <em>PHP Data Objects (Objetos de Dados PHP)</em></span></li>
				<li>Padão de Arquitetura: <span class="span-information">MVC - <em>Model View Controller (Modelo, Visão, Controlador)</em></span></li>
				<li>Modelo de Análise: <span class="span-information">OOP - <em>Object-Oriented Programming (Programação Orientada à Objetos)</em></span></li>
			</ul>
		</li>
		<li>
			DB:
			<ul>
				<li>
					MySQL: <span class="span-information">5.7</span>
				</li>
			</ul>
		</li>
	</ul>
</div>
