<div class="row justify-content-center mb-2">
    <div class="col-6 col-sm-6 col-md-8 col-lg-8">
        <h5 class="font-weight-bold text-primary">LISTA DE <?= mb_convert_case($this->type, MB_CASE_UPPER, "UTF-8");?></h5>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-sm-6">
        <canvas id="myChart" width="400" height="250"></canvas>
    </div>
</div>
<script src="<?= JS_PATH;?>/global/Chart.bundle.min.js" type="text/javascript"></script>
<script type="text/javascript">
    var ctx = document.getElementById('myChart');
    var myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: [<?= $this->{$this->type}->description;?>],
            datasets: [{
                label: '# of Votes',
                data: [12],
                backgroundColor: [
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 99, 132, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });

</script>