<div class="row justify-content-center mb-2">
    <div class="col-6 col-sm-3 col-md-8 col-lg-8">
        <h5 class="font-weight-bold text-primary">LISTA DE CATEGORIAS</h5>
    </div>
    <div class="col-6 col-sm-6 col-md-2 col-lg-2">
        <a href="/category/register" class="btn btn-sm btn-primary float-right"><i class="fas fa-plus pr-2"></i> Nova Categoria</a>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-8 col-sm-8 col-md-10 col-lg-10">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Descrição</th>
                    <th>ÍCONE</th>
                    <th>COR</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php if (is_array($this->categories) && !empty($this->categories)): ?>
                    <?php foreach ($this->categories as $key => $category): ?>
                        <tr>
                            <td><?= $category->id;?></td>
                            <td><?= $category->description;?></td>
                            <td><?= $category->icon;?></td>
                            <td><?= $category->color;?></td>
                            <td class="text-center">
                                <a href="/category/edit/<?= $category->id;?>" title="Editar" class="px-2 text-info btnUserEdit">
                                    <i class="far fa-edit"></i>
                                </a>
                                <a title="Excluir" class="px-2 text-danger pointer btnCategoryDelete" data-category-delete="<?= $category->id;?>">
                                    <i class="far fa-minus-square"></i>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td class="text-center" colspan="6">
                            <span class="font-weight-light text-danger font-weight-bold">Nenhuma categoria cadastrada!</span>
                        </td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

