<div class="row justify-content-center">
    <div class="col-sm-10 col-md-10 col-lg-6 col-xl-6">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">CADASTRAR CATEGORIA</h6>
            </div>
            <div class="card-body">
                <form id="formRegisterCategory" name="formRegisterCategory" method="POST" action="">
                    <div class="form-group">
                        <label for="description">Descrição</label>
                        <input type="text" class="form-control input-uppercase" id="description" name="description" required data-validation="required">
                    </div>
                    <div class="form-group">
                        <label for="icon">Ícone</label>
                        <input type="text" class="form-control" id="icon" name="icon">
                    </div>
                    <div class="form-group">
                        <label for="color">Cor</label>
                        <input type="text" class="form-control" id="color" name="color">
                    </div>
                    <button id="btnFormRegisterCategory" type="button" class="btn btn-primary float-right">Salvar</button>
                </form>
            </div>
        </div>
    </div>
</div>